### ISSUE TITLE
Bug - Transaction Drop Point Feature

### ISSUE THREAD

**Issue by winandagreaceas** [RecyThing/RecyThing-Web#136]
The issue revolves around the absence of mandatory validation for the "Jenis Sampah" field when adding a new transaction. 

When attempting to add a new transaction without specifying the waste type, the system currently allows the transaction to be successfully added to the data table. As per the intended design, this field is crucial for accurately tracking the point acquisition after waste management transactions. 

<img width="960" alt="image" src="https://github.com/RecyThing/RecyThing-Web/assets/133995819/6ace6697-a539-4796-8efe-68c4e8cf131d">

<img width="960" alt="image" src="https://github.com/RecyThing/RecyThing-Web/assets/133995819/4ab433a5-9a5c-4a5c-8698-ba6aa30c6dd3">

**Comment by TaksaWibawa** [comment]
![image](https://github.com/RecyThing/RecyThing-Web/assets/98959851/ba167d69-e44f-4817-b6f8-7438690b71a9)

fixed the bug by set by default to be always one trash type field to be filled @winandagreaceas
